name: Setup apache spark
description: "Download and install Apache spark based versioned according to variables"
inputs:
  spark-version: 
    required: true
  hadoop-version:
    required: true
  py4j-version: 
    required: false
    default: "0.10.9"
  scala-version: 
    required: false
    default: ""

runs:
  using: composite
  steps:
    # - name: Test inputs
    #   shell: bash
    #   run: |
    #     echo ${{ inputs.spark-version }}
    - name: Setup apache spark
      shell: bash
      run: |
        bash ./.github/workflows/setup-spark.sh
      env:
        SPARK_VERSION: ${{ inputs.spark-version }}
        HADOOP_VERSION: ${{ inputs.hadoop-version }}
        PY4J_VERSION: ${{ inputs.py4j-version }}
        SCALA_VERSION: ${{ inputs.scala-version }}
    - name: Test Spark Installation
      shell: bash
      run: | 
        echo "$SPARK_HOME"
        spark-submit --version

    
