name: Test Spark Setup
on:
  push:
    branches:

jobs:
  test-spark-setup:
    name: Test spark setup
    runs-on: 'ubuntu-latest'
    env:
      spark-version: "3.2.1"
      hadoop-version: "3.2"
      py4j-version: "0.10.9"
      scala-version: ""

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Check Python install
        run: |
          PY_VERSION=$(python3 --version)
          echo $PY_VERSION
      - name: Check Java install
        run: |
          JAR_VERSION=$(java -version)
          echo $JAR_VERSION
      - name: Setup Apache spark
        uses: ./
        with:
          spark-version: "3.2.1"
          hadoop-version: "3.2"
          py4j-version: "0.10.9"
          scala-version: ""
  
