name: Test Spark Setup
on:
  push:
    branches:

jobs:
  test-spark-setup:
    name: Test spark setup
    runs-on: 'ubuntu-latest'
    env:
      spark-version: '99999999'
      hadoop-version: '11111111'

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Check Python install
        run: |
          PY_VERSION=$(python3 --version)
          echo $PY_VERSION
      - name: Check Java install
        run: |
          JAR_VERSION=$(java -version)
          echo $JAR_VERSION
      - name: Install spark
        # inputs:
        #   spark-version:
        #     required: true
        #   hadoop-version:
        #     required: true
        #   scala-version:
        #     required: false
        #     default: ""
        #   py4j-version:
        #     required: false
        #     default: "0.10.9"

        run: bash ./.github/workflows/setup-spark.sh ${{ env.spark-version }} ${{ env.hadoop-version }}
        # with:
        #   spark-version: "9999999"
        #   hadoop-version: "11111111"

  
      - name: Test Spark Installation
        run: | 
          echo "$SPARK_HOME"
          spark-submit --version