name: Test Spark Setup
on:
  push:
    branches:
      - main

jobs:
  test-spark-setup:
    name: Test spark setup
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Check Python install
        run: |
          PY_VERSION=$(python3 --version)
          echo $PY_VERSION

      - name: Check Java install
        run: |
          JAR_VERSION=$(java -version)
          echo $JAR_VERSION

      - name: Install spark
        run: |
          echo 'Workspace: $GITHUB_WORKSPACE'
          IFS='/'
          read -a path_parts <<< "$GITHUB_WORKSPACE"
          echo "There are ${#path_parts[*]} words in the text."
          for ((idx=0; idx<${#path_parts[@]}-1; ++idx)); do
              echo "$idx" "${path_parts[idx]}"
          done
