name: Test Spark Setup
on:
  push:
    branches:
      - main

jobs:
  test-spark-setup:
    name: Test spark setup
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Check Python install
        run: |
          PY_VERSION=$(python3 --version)
          echo $PY_VERSION

      - name: Check Java install
        run: |
          JAR_VERSION=$(java -version)
          echo $JAR_VERSION

      - name: Install spark
        run: |
          # Debug
          echo "Workspace: $GITHUB_WORKSPACE"
          
          # Split string and insert into array
          IFS='/'
          read -a PATH_PARTS <<< "$GITHUB_WORKSPACE"

          # Iterate thru array and recreate path
          # Ignore last path part and empty strings
          INSTALL_FOLDER=''
          for ((idx=0; idx<${#PATH_PARTS[@]}-1; ++idx)); do
              # Debug
              echo "$idx" "${PATH_PARTS[idx]}"

              # Concat string
              if ! [   "${PATH_PARTS[idx]}" = ""  ];
              then 
                INSTALL_FOLDER+="/${PATH_PARTS[idx]}"
                # Debug
                echo "$INSTALL_FOLDER"
              fi
          done
          echo "Proposed install folder: $INSTALL_FOLDER"
          # Check if proposed folder is writable
          ls -l $INSTALL_FOLDER


