name: Test Spark Setup
on:
  push:
    branches:
      - main

jobs:
  test-spark-setup:
    name: Test spark setup
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Check Python install
        run: |
          PY_VERSION=$(python3 --version)
          echo $PY_VERSION

      - name: Check Java install
        run: |
          JAR_VERSION=$(java -version)
          echo $JAR_VERSION

      - name: Install spark
        run: |
          echo 'Workspace: $GITHUB_WORKSPACE'
          IFS='/'
          read -a strarr <<< "$GITHUB_WORKSPACE"
          echo "There are ${#strarr[*]} words in the text."
          for val in "${strarr[@]}";
          do
            printf "$val\n"
          done
